# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: users

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs6.10
  profile: tutor_server


# The `functions` block defines what code to deploy
functions:
  register:
    handler: register/handler.register
    # The `events` block defines how to trigger the handler.register code
    events:
      - http:
          path: register
          method: post
          cors: true
          integration: lambda

  login:
    handler: login/handler.login
    # The `events` block defines how to trigger the handler.login code
    events:
      - http:
          path: login
          method: post
          cors: true
          integration: lambda
